name: Packer-Backend

on:
  push:
    branches:
      - main
    paths:
      - 'infra/packer/backend/**'
      - 'apps/frontend/fleetApi/**'
env:
  WORKING_DIRECTORY: "./infra/packer/backend"
  PACKER_VERSION: "1.9.4"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

