name: Packer-Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'infra/packer/frontend/**'
#      - './../apps/fleetPortal/**'
env:
  WORKING_DIRECTORY: "./src/packer/frontend"
  PACKER_VERSION: "1.9.4"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJs
        uses: actions/setups-node@v4
        with:
          node-version: '20.x'
      - run: |
          npm ci
          npm build --prod
          npm run test
