name: Packer-Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'infra/packer/frontend/**'
      - 'apps/frontend/fleetPortal/**'
env:
  WORKING_DIRECTORY: "./src/packer/frontend"
  PACKER_VERSION: "1.9.4"
  ANGULAR_WORKING_DIRECTORY: "./apps/frontend/fleetPortal"
  PROJECT_NAME: "fleet-portal"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build
        working-directory: ${{ env.ANGULAR_WORKING_DIRECTORY }}
        run: |
          npm ci
          npm run build --prod

      - name: Generate Package
        run: zip -r ../deployment.zip ./
        working-directory: "${{env.ANGULAR_WORKING_DIRECTORY}}/dist/${{env.PROJECT_NAME}}"

      - name: Upload Deployment Package
        uses: actions/upload-artifact@v2
        with:
          name: angular-deployment
          path: ${{env.ANGULAR_WORKING_DIRECTORY}}/dist/deployment.zip