name: Terraform-Init

on:
  push:
    branches:
      - main
    paths:
      - './infra/terraform/**'
env:
  WORKING_DIRECTORY: "./src/packer/backend"
  PACKER_VERSION: "1.9.4"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

